CREATE DATABASE
  IF NOT EXISTS %MYSQL_DATABASE%
  CHARACTER SET = 'utf8';

GRANT ALL PRIVILEGES
  ON %MYSQL_DATABASE%.*
  TO '%MYSQL_USERNAME%'@'localhost'
  IDENTIFIED BY '%MYSQL_PASSWORD%';

FLUSH PRIVILEGES;